# - Find Intel MKL
#   MKL_INCLUDE_DIR      : mkl.h
#   MKL_LIBRARIES        : the library to link against.
#   MKL_FOUND

set(MKL_ROOT $ENV{MKLROOT})

IF(MKL_INCLUDE_DIRS)
  FIND_PATH(MKL_INCLUDE_DIR mkl.h ${MKL_INCLUDE_DIRS})
  FIND_LIBRARY(MKL_LIBRARY mkl ${MKL_LIBRARY_DIRS})
ELSE(MKL_INCLUDE_DIRS)
    SET(TRIAL_PATHS
      /usr/include
      /usr/local/include
      ${MKL_ROOT}/include
    )
    FIND_PATH(MKL_INCLUDE_DIR mkl.h ${TRIAL_PATHS})
ENDIF(MKL_INCLUDE_DIRS)
set(MKL_INCLUDE_DIRS ${MKL_INCLUDE_DIR} )

SET(MKL_FOUND FALSE)
IF(MKL_INCLUDE_DIR)
  MESSAGE(STATUS "MKL_INCLUDE_DIR=${MKL_INCLUDE_DIR}")
  SET(MKL_FOUND TRUE)
ENDIF()

MARK_AS_ADVANCED(
   MKL_INCLUDE_DIR
   MKL_FOUND
)
