# CPPTOML_INCLUDE_DIR = cpptoml.h
# CPPTOML_FOUND = true if CPPTOML is found

IF(CPPTOML_INCLUDE_DIRS)
  FIND_PATH(CPPTOML_INCLUDE_DIR cpptoml.h ${CPPTOML_INCLUDE_DIRS})
ELSE(CPPTOML_INCLUDE_DIRS)
    SET(TRIAL_PATHS
      $ENV{HOME}/installs/include
      /usr/include
      /usr/local/include
      /opt/homebrew/include
    )
    FIND_PATH(CPPTOML_INCLUDE_DIR cpptoml.h ${TRIAL_PATHS})
ENDIF(CPPTOML_INCLUDE_DIRS)
set(CPPTOML_INCLUDE_DIRS ${CPPTOML_INCLUDE_DIR})

IF(CPPTOML_INCLUDE_DIR)
  MESSAGE(STATUS "CPPTOML_INCLUDE_DIR=${CPPTOML_INCLUDE_DIR}")
  SET(CPPTOML_FOUND TRUE)
ELSE()
  MESSAGE("CPPTOML NOT found.")
  SET(CPPTOML_FOUND FALSE)
ENDIF()

MARK_AS_ADVANCED(
   CPPTOML_INCLUDE_DIR
   CPPTOML_FOUND
)
