name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    
    env:
      MKL_INC_DIR: /usr/include/mkl
      MKL_LIB_DIR: /usr/lib/x86_64-linux-gnu
      OMP_NUM_THREADS: 2

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        gfortran --version
        sudo apt-get install libmkl-dev libboost-dev
        cd /tmp
        wget https://github.com/wztzjhn/arpack-ng/archive/refs/heads/dev.zip
        unzip dev.zip
        cd arpack-ng-dev/
        sh bootstrap
        FFLAGS="-m64 -I${MKL_INC_DIR}" FCFLAGS="-m64 -I$MKL_INC_DIR" CFLAGS="-DMKL_ILP64 -m64 -I${MKL_INC_DIR}" CXXFLAGS="-DMKL_ILP64 -m64 -I${MKL_INC_DIR}" LIBS="-L${MKL_LIB_DIR} -Wl,--no-as-needed -lmkl_gf_ilp64 -lmkl_tbb_thread -lmkl_core -lpthread -lm -ldl" LIBSUFFIX="ILP64" INTERFACE64="1" ./configure --with-blas=mkl_gf_ilp64 --with-lapack=mkl_gf_ilp64 --enable-icb --prefix=$HOME/installs
        make check
        make install
    
    - name: make test
      run: |
        mkdir bin
        cd src; make test -j2
        cd ../bin; ./test.x
