name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    
    env:
      CFLAGS: '-DMKL_ILP64 -m64 -I/usr/include/mkl'
      CXXFLAGS: '-DMKL_ILP64 -m64 -I/usr/include/mkl'
      LIBS: '-L/usr/lib/x86_64-linux-gnu -Wl,--no-as-needed -lmkl_gf_ilp64 -lmkl_tbb_thread -lmkl_core -lpthread -lm -ldl'
      LIBSUFFIX: 'ILP64'
      INTERFACE64: '1'
      OMP_NUM_THREADS: 2

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        mkdir ~/installs
        mkdir ~/installs/lib
        mkdir ~/installs/include
        sudo apt-get update
        sudo apt-get install -y libmkl-dev libboost-dev
        cd /tmp
        wget https://github.com/wztzjhn/arpack-ng/archive/refs/heads/dev.zip
        unzip dev.zip
        cd arpack-ng-dev/
        sh bootstrap
        ./configure --enable-icb --with-blas=mkl_gf_ilp64 --with-lapack=mkl_gf_ilp64 --prefix=$HOME/installs
        make check
        make install
    
    - name: make test
      run: |
        export LD_LIBRARY_PATH=${HOME}/installs/lib:$LD_LIBRARY_PATH
        echo " ------ $LD_LIBRARY_PATH ------"
        mkdir bin
        cd src; make test -j2
        cd ../bin; ./test.x
